require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'
    - 'app/models/user.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/production.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
