default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= Rails.application.credentials[:postgresql][:DB_HOST] %>
  database: book_store_rg_development
  username: <%= Rails.application.credentials[:postgresql][:DB_USER] %>
  password: <%= Rails.application.credentials[:postgresql][:DB_PASSWORD] %>

test:
  <<: *default
  host: <%= Rails.application.credentials[:postgresql][:DB_HOST] %>
  database: book_store_rg_test
  username: <%= Rails.application.credentials[:postgresql][:DB_USER] %>
  password: <%= Rails.application.credentials[:postgresql][:DB_PASSWORD] %>
